site_name: My Documentation
theme:
  name: material
  nav:
  - Home: index.md
  - Overview:
      - Product Overview: overview/product-overview.md
  - Troubleshooting:
      - v5.0: troubleshooting/5.0-troubleshooting.md
site_url: https://tiwaryarchana.github.io/docs-as-code-practice/